In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [4]:
# Create a 1D numpy array
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
print(a,b)
print(type(a))
print(type(b))

[1 2 3 4 5] [ 6  7  8  9 10]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [5]:
print(a+b)
print(a*b)
print(a-b)

[ 7  9 11 13 15]
[ 6 14 24 36 50]
[-5 -5 -5 -5 -5]


np.array([[],[],[]])

In [4]:
n2 = np.array([[1,2],[2,3]])
print(n2)

[[1 2]
 [2 3]]


In [5]:
n3 = np.array([[1,2],[3,4],[5,6]])
print(n3)

[[1 2]
 [3 4]
 [5 6]]


In [6]:
print(n2.shape) # no of rows and columns
print(n2.ndim) # gives the dimension
print(n3.dtype) # gives the type of the matrix


(2, 2)
2
int64


In [10]:
np.arange(1,100,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [11]:
np.random.randint(1,100, size =(2,3))

array([[98, 85, 18],
       [84, 98, 60]], dtype=int32)

In [14]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x)
y = np.array([[1,2,3],[2,3,4],[3,4,5]])
print(y)
print(x.min(axis = 0))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [2 3 4]
 [3 4 5]]
[1 2 3]


In [15]:
print(x+y)
print(x-y)
print(x*y)

[[ 2  4  6]
 [ 6  8 10]
 [10 12 14]]
[[0 0 0]
 [2 2 2]
 [4 4 4]]
[[ 1  4  9]
 [ 8 15 24]
 [21 32 45]]


In [16]:
print(x@y)

[[14 20 26]
 [32 47 62]
 [50 74 98]]


In [17]:
x.prod()

np.int64(362880)

In [8]:
print(x.sum())
print(x.std())
print(x.var())

45
2.581988897471611
6.666666666666667


In [9]:
a = np.array([1,2,3,4,5,6,7,8,9])
print(np.percentile(a,50)) # median
print(np.percentile(a,25)) # 1st quartile
print(np.percentile(a,75)) # 3rd quartile

5.0
3.0
7.0


In [12]:
print(np.unique(x)) # returns uniques values

[1 2 3 4 5 6 7 8 9]


In [13]:
# reshape the array
a = np.random.randint(11,100, (4,4))
print(a)
print('2x8')
print(a.reshape(2,8))
print('8x2')
print(a.reshape(8,2))
print('2x2x4')
print(a.reshape(2,2,4))

[[64 54 37 66]
 [73 77 21 74]
 [48 74 19 38]
 [22 55 80 25]]
2x8
[[64 54 37 66 73 77 21 74]
 [48 74 19 38 22 55 80 25]]
8x2
[[64 54]
 [37 66]
 [73 77]
 [21 74]
 [48 74]
 [19 38]
 [22 55]
 [80 25]]
2x2x4
[[[64 54 37 66]
  [73 77 21 74]]

 [[48 74 19 38]
  [22 55 80 25]]]
