# Strings
- 1-10 done in strings file
- 23-25 also done in strings file

In [1]:
# 11
a = 15
print(f'The variable is {a}')

The variable is 15


In [5]:
# 12
s1 = 'python '
s2 = 'is '
s3 = 'great.'
mainstr = s1 + s2 + s3
print(mainstr)

python is great.


In [7]:
#13
print(" ".rjust(20,'#'))

################### 


In [9]:
#14
for num in range(1, 10):
    print(f'{num}.')
print()

1.
2.
3.
4.
5.
6.
7.
8.
9.



In [11]:
#15
sen = input("Enter a sentence: ")
word = sen.split()
print("\n".join(word))

My
name
is
Srishti


In [23]:
#16
str = input('Enter a sentence: ')
str.endswith('?')


True

In [21]:
#17
line = input("Enter a line: ")
print(line.count('e'))

2


In [22]:
#18
num = input("Enter something: ")
num.isdigit()

True

In [24]:
#19
text = '   this is not a good string           '
text.strip()


'this is not a good string'

In [27]:
#20
data = input("Enter a string: ")
for capital in data:
    if capital.isupper():
        print("found")
        break

found


In [28]:
#21
names = 'Joe, David, Mark, Tom, Chris, Robert'
names.split()

['Joe,', 'David,', 'Mark,', 'Tom,', 'Chris,', 'Robert']

In [1]:
#22
text = 'this is some text'
real = text.split()
for i in real:
    newtext = i + 'aye'
    print(newtext)


thisaye
isaye
someaye
textaye


# Loops

In [33]:
#1
for num in range(1, 11):
    print(num)

1
2
3
4
5
6
7
8
9
10


In [36]:
#2
n = 15
a = 1
while(a<11):
    print(f'{n} * {a} = {n*a}')
    a = a+1

15 * 1 = 15
15 * 2 = 30
15 * 3 = 45
15 * 4 = 60
15 * 5 = 75
15 * 6 = 90
15 * 7 = 105
15 * 8 = 120
15 * 9 = 135
15 * 10 = 150


In [42]:
#3
s = 0
for even in range(0,101,2):
    s = s + even
print(s)

2550


In [51]:
#4
num = 25
i = 25 
c = 0
while i > 0:
    if num % i == 0:
        c = c + 1 
    i = i - 1
if c > 2:
    print('Not Prime')
else:
    print('Prime')

Not Prime


In [55]:
#5
f = 1 
for fact in range(1,6):
    f = f * fact
print(f)

120


In [59]:
#6
a = 0
b = 1
print(a)
print(b)
for i in range(2,11):
    c = a + b 
    a = b
    b = c 
    print(c)



0
1
1
2
3
5
8
13
21
34
55


In [61]:
#7
max = 0
list = [12, 23, 134, 56, 67, 78, 90, 108]
for el in list:
    if el > max:
        max = el
print(max)

134


In [67]:
#8
str = "Hello"
rev = ''
length = len(str)
while length > 0:
    rev = rev + str[length -1]
    length = length - 1
print(rev)

olleH


In [73]:
#9
from string import ascii_uppercase
for alpha in ascii_uppercase:
    value = ord(alpha)
    print(value)

65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90


In [84]:
#10
str = 'wow'
palin = ''
length = len(str)
for word in str:
    palin = word + palin
if(palin == str):
    print("Palindrome")
else:
    print('Non-palindrome')


Palindrome


In [10]:
#11
list_num = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
total = 0
c = 0
avg = 0
for el in list_num:
    total = total + el
    c = c + 1
avg = total / c
print(f'the average of the list is: {avg:.2f}')

the average of the list is: 5.50


In [19]:
#12
list_numbers = [12, 34, 56, 78, 90, 23, 45, 9, 2, 100]
length = len(list_numbers)
count = 1
small = list_numbers[0]
while count != length:
    if list_numbers[count] < small:
        small = list_numbers[count]
    count = count + 1
print(f'The smallest element is: {small}')

The smallest element is: 2


In [4]:
#13
number = input('Enter a number: ')
s = 0
for digit in number:
    s = s + int (digit)
print(s)


15


In [23]:
#14
data = list(range(2001, 2011))
size = len(data)
part = 0
c = 0
while  part != size:
    if data[part] % 4 == 0:
        c = c + 1
        break
    else:
        part = part + 1
if c > 0:
    print('The list have a leap year in it')
else:
    print('The list does not have a leap year in it')



The list have a leap year in it


In [28]:
#15
table_num = [1, 2, 3, 4, 5]
for piece in table_num:
    for table in range(1,11):
        print(table * piece, end=" ")
    print()
print()


1 2 3 4 5 6 7 8 9 10 
2 4 6 8 10 12 14 16 18 20 
3 6 9 12 15 18 21 24 27 30 
4 8 12 16 20 24 28 32 36 40 
5 10 15 20 25 30 35 40 45 50 



In [31]:
#16
num = int(input("Enter a number"))
f = 1
for fact in range(1, num+1):
    f = f * fact
print(f)

120


In [32]:
#17
str = input("Enter a sentence: ")
str = str.lower()
vowel = 0
for alpha in str:
    if alpha == 'a' or alpha == 'e' or alpha == 'i' or alpha == 'o' or alpha == 'u':
        vowel = vowel + 1
print(f'The number of vowels are: {vowel}')

The number of vowels are: 5


In [38]:
#18
arr = [16, 27, 38, 45, 90, 100, 1, 35, 67, 98]
max = arr[0]
min = arr[0]
for el in arr:
    if el > max:
        max = el
    if el < min:
        min = el
print(f'The largest element of the array is: {max}')
print(f'The smallest element of the array is: {min}')

The largest element of the array is: 100
The smallest element of the array is: 1


In [44]:
#19
sen = input('Enter a sentence: ')
sen = sen + ' '
word = ''
new_sen = ''
for alphabet in sen:
    if alphabet != ' ':
        word = word + alphabet
    else:
        new_sen = word + ' ' + new_sen
        word = ''
print(new_sen)

you are how hello 


# Lists

In [3]:
#1
list = []
for i in range(10):
    list.append(int(input('Enter a number: ')))
print(list)

[45, 56, 54, 23, 12, 7, 8, 9, 10, 49]


In [6]:
#2
numbers = [12,34,56,21,38,90,67,76,54,1]
c = 0
search = int(input('Enter a number: '))
for i in numbers:
    if search == i:
        print('The number is in the list')
        c = c + 1
if c == 0:
    print('The number is not in the list')

The number is in the list


In [15]:
#3
names = ['ayush','shreya','mansi','omi','om']
names.sort()
print(names)

['ayush', 'mansi', 'om', 'omi', 'shreya']


In [1]:
#4
num = [12,34,56,65,40,100,2,5,67,10]
num.sort()
print(num[-1])


100


In [1]:
#5
list1 = [12,23,34,43,32,21,56,65,90,10]
list2 = [10,45,65,78,90,99,37,83,92,21]
for el in list1:
    for num in list2:
        if el == num:
            print(el)

21
65
90
10


In [9]:
#6
filename = ['file1.img', 'file2.img', 'file3.img', 'file4.jpg', 'file5.jpg', 'file6.jpg']
clean_file = list(filter(lambda i: not i.endswith('.img'),filename))
print(clean_file)

['file4.jpg', 'file5.jpg', 'file6.jpg']


In [1]:
#7
nested_list = [[1,2,3],[4,5,6],[7,8,9]]
print(nested_list[-1][0])

7


In [11]:
#8
num = [1,2,2,3,4,5,5,5,3,6]
num_set = set(num)
num_list = list(num_set)
print(num_list)

[1, 2, 3, 4, 5, 6]


In [12]:
#9
name = ['omi','om','shiv','srishti','khushi']
long = ''
for each in name:
    if len(each) > len(long):
        long = each
print(long)

srishti


In [17]:
#10
number = [34,43,5,65,11,90,12,2,46,77]
total = 0
for every in number:
    if every % 2 == 0:
        total = total + every
print(total)

184


In [48]:
#11
data = [45,67,89,54,42,34,11,90,12,2]
item = int(input("Enter the position of the number to be removed: "))
data.pop(item)
print(data)

[45, 67, 89, 54, 34, 11, 90, 12, 2]


In [21]:
#12
names = ['ayush','shreya','mansi','omi','om']
final_str = ''.join(names)
print(final_str)


ayushshreyamansiomiom


In [3]:
#13
data = [45,67,89,54,42,34,11,90,12,2]
if len(data) % 2 == 0:
    median = (len(data)+1)//2
else:
    median = (len(data)//2)+((len(data)//2)+1)
print(data[median])

34


In [38]:
#14
names.reverse()
print(names)

['om', 'omi', 'mansi', 'shreya', 'ayush']


In [4]:
#15
list_num = [12,23,45,67,85,66,42,23,45,14]
for value in list_num:
    avg = sum(data) / len(data)
print(avg)

44.6


In [2]:
#16
list_num = [12,23,45,67,85,66,42,23,45,14]
print(list_num.index(67))

3


In [7]:
#17
str = [' ram',' sita  ','ravaan','war of lanka ',' immortals of meluha']
new_str = []
for el in str:
    new_str.append(el.strip())
print(new_str)

['ram', 'sita', 'ravaan', 'war of lanka', 'immortals of meluha']


In [8]:
#18
list_num.sort(reverse = True)
print(list_num)

[85, 67, 66, 45, 45, 42, 23, 23, 14, 12]


In [9]:
#19
num = int(input("Enter a number: "))
list_num.insert(0,num)
print(list_num)


[45, 85, 67, 66, 45, 45, 42, 23, 23, 14, 12]


In [7]:
#20
list1 = [12,23,34,43,32,21,56,65,90,10]
list2 = [10,45,65,78,90,99,37,83,92,21]
list1.extend(list2)
print(list1)

[12, 23, 34, 43, 32, 21, 56, 65, 90, 10, 10, 45, 65, 78, 90, 99, 37, 83, 92, 21]


In [6]:
#21
numlist = [] 
for i in range(10):
    num = int(input('Enter a number: '))
    numlist.append(num)
newlist = list(map(lambda i: i ** 2, numlist))
print(newlist)

[144, 529, 1156, 484, 5929, 7921, 8100, 5776, 16, 11881]


In [1]:
#22
list_num = [12,23,45,67,85,66,42,23,45,14]
new_list = list(map(lambda i: str(i), list_num))
print(new_list)

['12', '23', '45', '67', '85', '66', '42', '23', '45', '14']


In [5]:
#23
list_num = [12,23,45,67,85,66,42,23,45,14]
add_list = list(map(lambda i: i + 10, list_num))
print(add_list)

[22, 33, 55, 77, 95, 76, 52, 33, 55, 24]


In [1]:
#24
str = []
for i in range(5):
    el = input('Enter series name: ')
    str.append(el)
new_str = list(map(lambda i: i[0], str))
print(new_str)

['l', 'o', 'g', 't', 'i']


In [2]:
#25
temp = [34, 23, 50, 65, 12, 5, 10, 57, 100, 42]
fah = list(map(lambda i: i + 273, temp))
print(fah)

[307, 296, 323, 338, 285, 278, 283, 330, 373, 315]


In [8]:
#26
list_num = ['12','23','45','67','85','66','42','23','45','14']
int_list = list(map(lambda i: int(i),list_num))
print(int_list)

[12, 23, 45, 67, 85, 66, 42, 23, 45, 14]


In [11]:
#27
name = ['omi','om','shiv','srishti','khushi']
length = list(map(lambda i: len(i), name))
print(length)

[3, 2, 4, 7, 6]


In [17]:
#28
numberlist = [1,4,9,16,25]
sqroot = list(map(lambda i: i ** (1/2), numberlist))
print(sqroot)

[1.0, 2.0, 3.0, 4.0, 5.0]


In [1]:
#29
neg_list = [-5,4,-3,-7,5]
abs = list(map(lambda i: abs(i),neg_list))
print(abs)

[5, 4, 3, 7, 5]


In [25]:
#30
books = []
for b in range(5):
    book = input('Enter a book name: ')
    books.append(book)
up = list(map(lambda i: i.upper(), books))
print(up)

['RAM', 'SITA', 'RAAVAN', 'WAR OF LANKA', 'NOVEMBER 9']


In [24]:
#31
user = []
for i in range(10):
    each = int(input('Enter a number: '))
    user.append(each)
even = list(filter(lambda i: i%2==0, user))
print(even)

[34, 12, 56, 66, 66, 78]


In [7]:
#32
fruits = []
for i in range(5):
    el = input('Enter a fruit name: ')
    fruits.append(el.lower())
f = lambda i: i.startswith('a') or i.startswith('e') or i.startswith('i') or i.startswith('o') or i.startswith('u') 
vow_start = list(filter(f,fruits))
print(vow_start)

['apple', 'elderberry', 'orange']


In [13]:
#33
places = []
for p in range(5):
    city = input('Enter a city: ')
    places.append(city)
new_places = list(filter(lambda i: len(i)>5, places))
print(new_places)

['lucknow', 'jodhpur', 'kanpur']


In [12]:
#34
num = []
for i in range(10):
    n = int(input('Enter a number: '))
    num.append(n)
new_num = list(filter(lambda i: i>-1, num))
print(new_num)

[12, 34, 0, 54, 4, 1]


In [5]:
#35
animal = []
for a in range(5):
    ani = input('Enter an animal name: ')
    animal.append(ani)
new_animal = list(filter(lambda i: i.count('e') > 0, animal))
print(new_animal)

['donkey', 'monkey', 'elephant']


In [6]:
#36
main_list = []
list1 = []
list2 = []
for i in range(3):
   a = int(input('Enter a number: '))
   list1.append(a)
for j in range(3):
   b = int(input('Enter a number: '))
   list2.append(b)
for k in range(3):
   ml = [list1[k],list2[k]]
   main_list.append(ml)
print(main_list)

[[1, 4], [2, 5], [3, 6]]


In [22]:
#37
things = []
for i in range(5):
    el = input('Enter a non-living thing: ')
    things.append(list(el))
nested_list = list(map(lambda j: list(j), things))
print(nested_list)

[['t', 'o', 'y'], ['c', 'a', 'r'], ['b', 'i', 'k', 'e'], ['p', 'e', 'n'], ['p', 'e', 'n', 'c', 'i', 'l']]


In [3]:
#38
num = []
for i in range(5):
    n = int(input('Enter a number: '))
    num.append(n)
sq = list(map(lambda i: [i, i**2],num))
print(sq)

[[1, 1], [2, 4], [3, 9], [4, 16], [5, 25]]


In [18]:
#39
fruit = []
for i in range(3):
    f = input('Enter a fruit: ')
    fruit.append(f)
uni = list(map(lambda i: list(set(i)), fruit))
print(uni)

[['e', 'p', 'l', 'a'], ['n', 'a', 'b'], ['e', 'h', 'y', 'c', 'r']]


In [9]:
#40
number = []
fact = []
ml = []
for i in range(5):
    nb = int(input('Enter a number: '))
    number.append(nb)
for j in number:
    for k in range(1,j+1):
        if j % k == 0:
            fact.append(k)
        if j == k:
            ml.append([j, fact])
            fact = []
print(ml)

[[1, [1]], [2, [1, 2]], [3, [1, 3]], [4, [1, 2, 4]], [5, [1, 5]]]


In [32]:
#41
def reverse_list(nums):
    rev = nums[::-1]
    return rev

In [5]:
reverse = reverse_list([1,2,3,4,5])
print(reverse)

[5, 4, 3, 2, 1]


# Dictionary

In [15]:
#1 error
d = {
    str : "Hello"
    }
count = {}
i = 1
for k,v in d.items():
    count = count.update(i)
    i = i + 1
print(count)



TypeError: 'int' object is not iterable

In [16]:
#2
dict1 = {"a": 1, "b": 2}
dict2 = {"c": 3, "d": 4}
dict1.update(dict2)
print(dict1)

{'a': 1, 'b': 2, 'c': 3, 'd': 4}


In [36]:
#3
data = {"a": 10, "b": 5, "c": 10}
max(data.values())

10

In [26]:
#4
num = {"a": 1, "b": 2, "c": 3}
'd' in num.keys()

False

In [27]:
#5
num = {"a": 1, "b": 2, "c": 3}
num.pop('b')
print(num)

{'a': 1, 'c': 3}


In [40]:
#6 error
dict1 = {"a": 1, "b": 2, "c": 3}
dict2 = {"b": 3, "c": 4, "d": 5}
for k,v in dict1.items():
    if k == dict2.keys():
        print(k)


In [31]:
#7
n = {"a": 1, "b": 2, "c": 3}
len(n)

3

In [34]:
#8
dic = {"b": 2, "a": 1, "c": 3}
print(sorted(dic.items()))

[('a', 1), ('b', 2), ('c', 3)]


In [35]:
#9
val = {"a": 10, "b": 5, "c": 15}
min(val.values())

5

In [39]:
#10
n = {"a": 1, "b": 2, "c": 3}
list(n.values())

[1, 2, 3]

In [46]:
#11
n = {"a": 1, "b": 2, "c": 3}
num = 2
num in n.values()

True

In [26]:
#12
key = [1,2,3,4,5,6,7,8,9,10]
dict = {}
for j in key:
    dict[j] = j**2
print(dict)

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100}


In [ ]:
#13 error


In [12]:
#14
data = {"a": 1, "b": 2, "c": 3}
data.clear()
print(data)

{}


In [19]:
#15 error
data = {"a": 1, "b": 2, "c": 3}
tup = tuple(data.values())
print(tup)

(1, 2, 3)


In [16]:
#16
data = {"a": 1, "b": 2, "c": 3}
data_set = set(data.values())
if len(data.values()) == len(data_set):
    print('The values are unique')
else:
    print('The values are not unique')

The values are unique


In [18]:
#17 error
d = {"a": 1, "b": {"c": 2, "d": 3}, "e": 4}
list(d.values())

[1, {'c': 2, 'd': 3}, 4]

In [25]:
#18 error
pairs = {"a": 10, "b": 5, "c": 10}
max(pairs.values())
print(max(pairs.keys()) ,max(pairs.values()))

c 10


In [37]:
#19 error
keys = ["a", "b", "c"]
values = [1, 2, 3]
ans = list(zip(keys, values, strict=True))
print(dict(ans))

TypeError: 'dict' object is not callable

In [34]:
#20
data = {"a": 1, "b": 2, "c": 3}
for k,v in data.items():
    print(k,v)

a 1
b 2
c 3


# Numpy

In [2]:
import numpy as np

In [3]:
#1
b = np.zeros(10)
print(b)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [17]:
#2
c = np.ones(10)
print(c)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [18]:
#3
m = np.random.randint(0,9, (3,3))
print(m)

[[5 3 8]
 [6 0 2]
 [2 6 7]]


In [25]:
#4
arr = np.array([0,1,2,3,4,5,6,7,8,9])
print(np.flip(arr))

[9 8 7 6 5 4 3 2 1 0]


In [24]:
#5
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [28]:
#6
arr = np.array([0,1,2,3,4,5,6,7,8,9])
print(sum(arr))
print(arr.mean())
print(f'{arr.std():.2f}')

45
4.5
2.87


In [31]:
#7
matrix = np.random.randint(0,100, (5,5))
print(matrix)
print(matrix.min())
print(matrix.max())

[[41 80 87 60 67]
 [62 84  1 28 63]
 [10  0 21 97 10]
 [73  7 64 68 17]
 [48 48 23 54 16]]
0
97


In [8]:
#8 error
arr = np.zeros((4,4))
print(arr)
np.ones()




[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


TypeError: only integer scalar arrays can be converted to a scalar index

In [8]:
#9
m1 = np.random.randint(0,10, (3,3))
print(m1)
m2 = np.random.randint(0,10, (3,3))
print(m2)
print(m1*m2)

[[4 6 8]
 [5 3 9]
 [7 0 2]]
[[4 1 7]
 [9 6 7]
 [3 9 7]]
[[16  6 56]
 [45 18 63]
 [21  0 14]]


In [11]:
#10
print(np.unique(m2))

[1 3 4 6 7 9]


In [11]:
#11
mtrx = np.random.randint(0,100,(5,5))
print(mtrx)
print(mtrx[:,0::2])

[[43 76 80 81 39]
 [24 53 95 52 43]
 [68 45 54 15 54]
 [11 15 48 26 86]
 [ 1 44 59 51 91]]
[[43 80 39]
 [24 95 43]
 [68 54 54]
 [11 48 86]
 [ 1 59 91]]


In [12]:
#12
print(mtrx[1::2])

[[24 53 95 52 43]
 [11 15 48 26 86]]


In [13]:
#13
print(mtrx[:3,1:5])

[[76 80 81 39]
 [53 95 52 43]
 [45 54 15 54]]


In [19]:
#14
print(mtrx[::-1])

[[ 1 44 59 51 91]
 [11 15 48 26 86]
 [68 45 54 15 54]
 [24 53 95 52 43]
 [43 76 80 81 39]]


In [10]:
#15 error
a = [1,2,3,4,5]
np.diagonal(a,axis1=0, axis2=a ** 2)

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'